- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  apt:
    name: grafana
    update_cache: yes

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes